### ISSUE TITLE
Not support Python 3.4.2 in PyPi

### ISSUE THREAD

**Issue by shinznatkid** [mikeorr/Unipath#18]
Can use from github clone version but cannot use from pip3 install unipath.

C:\>pip3 freeze
Unipath==1.0

C:\>python3
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from unipath import Path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\unipath\__init__.py", line 4, in <module>
    from unipath.abstractpath import AbstractPath
  File "C:\Python34\lib\site-packages\unipath\abstractpath.py", line 11, in <module>
    _base = os.path.supports_unicode_filenames and unicode or str
NameError: name 'unicode' is not defined

**Comment by mikeorr** [comment]
Released version 1.1.

**Comment by shinznatkid** [comment]
Thankyou. :)
